# SQLite datasource
spring.datasource.url=jdbc:sqlite:presensi_astra.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate & JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true

# Fix untuk bean overriding (hindari konflik HikariCP metadata)
spring.main.allow-bean-definition-overriding=true